# -*- coding: utf-8 -*-
"""Day6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weJzOPHxfgP34fVCRwqrc8dfZLCPYhF3
"""

!pip install transformers datasets sentence-transformers diffusers accelerate huggingface_hub[cli] torchvision pillow sklearn --q

from transformers import pipeline
classifier=pipeline("sentiment-analysis",model="distilbert-base-uncased-finetuned-sst-2-english")
text=input("Enter a text to analyse:")
result=classifier(text)
print(result)

from transformers import pipeline
generator=pipeline("text-generation",model="gpt2")
prompt="In a future where healthcare is fully decentralized,"
output=generator(prompt,max_length=80,do_sample=True,temperature=0.8,top_p=0.9,num_return_sequences=2)
for i,out in enumerate(output):
  print(f"---generated(i)---")
  print(out["generated_text"])

from getpass import getpass
import os
hf_token=getpass("Enter your hugging face token")
os.environ["HF_TOKEN"]=hf_token

from huggingface_hub import InferenceClient
import os

MODEL_ID="meta-llama/Meta-Llama-3-8B-Instruct"
client=InferenceClient(token=os.environ["HF_TOKEN"],model=MODEL_ID)

def extract_text(rep):
  try:
    return rep['choices'][0]['message']['content']
  except Exception:
    return str(rep)

messages=[
    {"role":"system","content":"You are a helpful Leetcode problem solve"},
    {"role":"user","content":"Explain two Sum problem code simply with a python example"}
]

resp=client.chat_completion(messages,max_tokens=400)
print(extract_text(resp))