# -*- coding: utf-8 -*-
"""Student_Data_Explorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XUg9ItyKwRbNkqZJNcQXZONk4CfDGeI
"""

import pandas as pd

data = {
    "name": ["Arun", "Priya", "Kavin", "Sneha", "Rahul","Divya", "Vijay", "Anu", "Ramesh", "Keerthi"],
    "gender": ["Male", "Female", "Male", "Female", "Male","Female", "Male", "Female", "Male", "Female"],
    "department": ["CSE", "ECE", "EEE", "CSE", "ECE","IT", "CSE", "IT", "EEE", "ECE"],
    "math_score": [85, 92, 76, 88, 69, 95, 80, 91, 72, 84],
    "programming_score": [90, 85, 70, 95, 60, 98, 75, 89, 65, 80],
    "attendance_percentage": [96, 88, 70, 92, 68, 99, 85, 90, 72, 87]
}

df = pd.DataFrame(data)

df["total_score"] = df["math_score"] + df["programming_score"]

print(df)

print("\nDATASET OVERVIEW")
print("Total number of students:", len(df))
print("Total number of columns:", len(df.columns))
print("Unique departments:", df["department"].nunique())

print("\nDEPARTMENT WISE ANALYSIS")
dept_count = df["department"].value_counts()
print(dept_count)

print("\nSCORE ANALYSIS")
print("Highest Math Score:", df["math_score"].max())
print("Lowest Math Score:", df["math_score"].min())
print("Average Math Score:",df["math_score"].mean())
print("Average Programming Score:",df["programming_score"].mean())
print("Average Attendance Percentage:",df["attendance_percentage"].mean())

print("\nGENDER WISE ANALYSIS")
gender_avg = df.groupby("gender")["total_score"].mean()
print(gender_avg)

print("\nTOP 5 PERFORMERS")
top_students = df.sort_values(
    by="total_score",
    ascending=False
).head(5)
for index, row in top_students.iterrows():
    print(f"Name: {row['name']}")
    print(f"Department: {row['department']}")
    print(f"Total Score: {row['total_score']}")

print("\nATTENDANCE ANALYSIS")
low_attendance = df[df["attendance_percentage"] < 75]
if len(low_attendance) > 0:
    for index, row in low_attendance.iterrows():
        print(f"Name: {row['name']}")
        print(f"Department: {row['department']}")
        print(f"Attendance: {row['attendance_percentage']}%")
else:
    print("All students have attendance above 75%")

ece_students = df[df["department"] == "ECE"]
print("Number of ECE students:",len(ece_students))

female_avg_attendance = df[df["gender"] == "Female"]["attendance_percentage"].mean()
print("Average attendance of female students:",female_avg_attendance)

lowest_prog = df.loc[df["programming_score"].idxmin()]
print("Student with lowest programming score:")
print(lowest_prog["name"])

above_80 = df[df["math_score"] > 80]
print("Number of students scored above 80 in math:",len(above_80))

high_attendance = df[df["attendance_percentage"] > 90]
avg_total = high_attendance["total_score"].mean()
print("Average total score:",avg_total)

