# -*- coding: utf-8 -*-
"""DAY2_Mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YElGTyRtVe2jvP1P089b6O1XmkWkg0cy
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("student_performance.csv")

df["total_score"] = (
    df["math_score"] +
    df["programming_score"] +
    df["attendance_percentage"]
)

avg_math = df.groupby("department")["math_score"].mean()

dept_count = df["department"].value_counts()

top_students = df.sort_values(
    by="total_score",
    ascending=False
).head(8)

gender_attendance = df.groupby("gender")[
    "attendance_percentage"
].mean()


fig, axes = plt.subplots(2, 2, figsize=(16,10))

axes[0,0].bar(
    avg_math.index,
    avg_math.values
)

axes[0,0].set_title("Avg Math Score by Department")

for i, value in enumerate(avg_math.values):
    axes[0,0].text(
        i,
        value + 1,
        f"{value:.1f}",
        ha='center'
    )

axes[0,1].pie(
    dept_count.values,
    labels=dept_count.index,
    autopct='%1.0f%%'
)

axes[0,1].set_title("Students per Department")

axes[1,0].barh(
    top_students["name"],
    top_students["total_score"]
)

axes[1,0].invert_yaxis()

axes[1,0].set_title("Top 8 Students — Total Score")

axes[1,1].bar(
    gender_attendance.index,
    gender_attendance.values
)

axes[1,1].set_title("Avg Attendance by Gender")

fig.suptitle(
    "Student Performance Dashboard — Codeboosters Tech Internship",
    fontsize=18,
    fontweight='bold'
)

plt.tight_layout()
plt.show()

import pandas as pd
import sqlite3

df = pd.read_csv("student_performance.csv")

conn = sqlite3.connect("students.db")

df.to_sql(
    "students",
    conn,
    if_exists="replace",
    index=False
)

query = """
SELECT AVG(programming_score) AS avg_programming_score
FROM students
WHERE gender = 'Female';
"""
result = pd.read_sql_query(query, conn)
print(result)

"""Difference between WHERE and HAVING

WHERE:
Filters rows before grouping
Cannot use aggregate functions directly
Works on individual rows

HAVING:
Filters grouped data after GROUP BY
Used with aggregate functions like AVG(), SUM()
Works on grouped results
"""

query_where = """
SELECT *
FROM students
WHERE gender = 'Female';
"""
result_where = pd.read_sql_query(query_where, conn)
print(result_where)

query_having = """
SELECT department,
       AVG(math_score) AS avg_math
FROM students
GROUP BY department
HAVING AVG(math_score) > 70;
"""
result_having = pd.read_sql_query(query_having, conn)
print(result_having)

query3 = """
SELECT department,
       AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance_percentage) > 85;
"""

result3 = pd.read_sql_query(query3, conn)

print(result3)

