# -*- coding: utf-8 -*-
"""DAY_2_Database_SQL_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPh5ZOmoWzWr65FNP012xSGx_flzWfd3
"""

import sqlite3
#py built in db lib,no pip install needed
import pandas as pd
#for data frame
import matplotlib.pyplot as plt
#plotting submodule for mathplot
import warnings
#supress non critical warning message
warnings.filterwarnings('ignore')
print("All libraries imported successfully")
print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.version}")

df=pd.read_csv('/content/student_performance.csv')

print(f"Dataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns:{df.columns.tolist()}")
print("\nFirst 3 rows:")
df.head(3)

conn = sqlite3.connect('college.db')
cursor = conn.cursor()
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)
cursor.execute("SELECT COUNT(*) FROM students")
count = cursor.fetchone()[0]
print(f"Database 'college.db' created successfully!")
print(f"Table 'students' has {count} rows")

cursor.execute("PRAGMA table_info(students)")
columns_info = cursor.fetchall()
print("Table structure of 'students':")
print(f"{'Column Name' :<25} {'Data Type' :<12}")
print("-" * 38)
for col in columns_info:
  print(f"{col[1]:<25} {col[2]:<12}")

def run_query(sql, description=""):
  if description:
    print(f"\n{'='*55}")
    print(f"{description}")
    print(f"{'='*55}")
    result = pd.read_sql_query(sql, conn)
    print(result)

query1 = """
    SELECT student_id, name, department, math_score, attendance_percentage
    FROM students
    LIMIT 10
"""
result1 = run_query(query1, "Query 1: First 10 Students(SELECT + LIMIT)")
print(result1)

query1 = """
    SELECT student_id, name, department, math_score, attendance_percentage
    FROM students
    LIMIT 5 OFFSET 25
"""
result1 = run_query(query1, "Query 1: Last 5 Students")
print(result1)

query2 = """
   SELECT name, department, math_score
   FROM students
   ORDER BY math_score DESC
   LIMIT 5
"""
result2 = run_query(query2, "Query 2: Top 5 Students by Math Score")
print(result2)

query2 = """
   SELECT student_id, name, department, math_score, attendance_percentage, programming_score
   FROM students
   WHERE programming_score > 50 AND programming_score < 75
"""
result2 = run_query(query2, "Query 2: Students with programming_score between 50 and 75")
print(result2)

query3 = """
    SELECT name, math_score, science_score, programming_score, attendance_percentage
    FROM students
    WHERE department = 'Computer Science'
    ORDER BY programming_score DESC
"""
result3 = run_query(query3, "Query 3: Computer Science Students by Programming Score")
print(result3)

query3 = """
    SELECT department, student_id, name, programming_score, math_score, attendance_percentage
    FROM students
    WHERE department IN ('Electrical', 'Civil', 'Computer Science')
    ORDER BY programming_score DESC
    LIMIT 5
"""
result3 = run_query(query3, "Query 3: Top Students from Departments")
print(result3)

query4 = """
    SELECT name, department, attendance_percentage
    FROM students
    WHERE attendance_percentage > 90
    AND department != 'Civil'
    ORDER BY attendance_percentage DESC
"""
result4 = run_query(query4, "Query 4: Students with High Attendance")
print(result4)

dept_data = {
    'dept_code': ['CS', 'EC', 'CE','ME'],
    'dept_name': ['Computer Science', 'Electrical', 'Civil', 'Mechanical'],
    'hod_name': ['Dr.Sharma', 'Dr.Reddy', 'Dr.Patel', 'Dr.Kumar'],
    'established': [1985,1988,1972,1965],
    'intake': [60,60,60,60]
}
dept_df = pd.DataFrame(dept_data)
dept_df.to_sql('departments', conn, if_exists='replace', index=False)
print("Created 'departments' table:")
print(dept_df.to_string(index=False))
dept_map = {
    'Computer Science': 'CS',
    'Electrical': 'EC',
    'Civil': 'CE',
    'Mechanical': 'ME'
}
df['department_code'] = df['department'].map(dept_map)
df.to_sql('students', conn, if_exists='replace', index=False)
print("\nUpdated 'students' table with dept_code column:")

query_join="""
      SELECT
      s.name,
      s.math_score,
      d.dept_name,
      d.hod_name,
      d.established
      FROM students s
      INNER JOIN departments AS d ON s.department=d.dept_name
      ORDER BY s.math_score DESC
      LIMIT 8
"""
result=run_query(query_join,"Query")

chart1_sql = """
    SELECT department, ROUND(AVG(math_score), 2) AS avg_math
    FROM students
    GROUP BY department
    ORDER BY avg_math DESC
"""
chart1_data = pd.read_sql_query(chart1_sql, conn)
fig, ax = plt.subplots(figsize=(10,6))
n,bins