# -*- coding: utf-8 -*-
"""Day 9.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KL_x5WpTUmXkUMoseI2mHXFXPzCw2vh
"""

!pip install crewai --force-reinstall litellm==1.30.0 --force-reinstall requests python-dotenv apscheduler --q

import os
os.environ["GROQ_API_KEY"] = "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"

from crewai import Agent,Task,Crew
def research_agent_example():
  researcher = Agent(
      role='Research Analysis',
      gmail='identify top AI trends fro 2025',
      backstory='Expericenced technology researcher with 10+ years of industry experince',
      verbose = True,
      llm='groq/llama-3.3-70b-versatile'
  )
  research_task = Task(
      description='List and analyze the top 3 AI  trends for 2025 with examples',
      expected_outputs = 'Comprehensive report with detailed explanation of each trend',
      agent=researcher,
  )
  crew = Crew(
      agents=[researcher],
      tasks=[research_task],
      verbose=True,
  )
  return crew.kickoff()