# -*- coding: utf-8 -*-
"""Day_7_DE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilquoiROsi4WVCG0f_HA8hsJJz2UHfTy
"""

!pip uninstall -y chromadb
!pip install numpy==1.26.4
!pip install chromadb==0.5.5 sentence-transformers pandas

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
import chromadb

print("All libraries imported successfully")

documents = [
    "ETL is used to clean and transform data",
    "A vechile is a mode of transportation",
    "Cars and trucks are popular automboile",
    "SQL is used to query datasets",
    "Machine learning trains models on data",
]

print("Loading embedding model...")
model = SentenceTransformer("all-MiniLM-L6-v2")
print("Model loaded successfully")
print(f"Model products vectors of size: {model.get_sentence_embedding_dimension()}")

sentence = "ETL is used to clean and transform data"
embedding = model.encode(sentence)
print(f"Input Sentence: '{sentence}'")
print()
print(f"Embedding Type: {type(embedding)}")
print(f"Embedding Shape: {embedding.shape}")
print(f"First 10 Numbers: {embedding[:10].round(4)}")
print(f"Min Value: {embedding.min():.4f}")
print(f"Max Value: {embedding.max():.4f}")

sentence = [
    "ETL is used to clean and transform data",
    "Data transformation is a key pipleline step",
    "The sky is blue and the clouds are white",
]
embeddings = model.encode(sentence)
print(f"Number of sentences: {len(sentence)}")
print(f"Shape of embedding array: {embeddings.shape}")
print()
print("Each row is one sentence's encoding:")

def cosine_similarity(vec_a,vec_b):
  dot_product=np.dot(vec_a,vec_b)
  norm_a=np.linalg.norm(vec_a)
  norm_b=np.linalg.norm(vec_b)
  return dot_product/(norm_a*norm_b)
sin_01=cosine_similarity(embeddings[0],embeddings[1])
sin_02=cosine_similarity(embeddings[0],embeddings[2])
sin_12=cosine_similarity(embeddings[1],embeddings[2])
print("cosine similarity scores")
print("="*60)
print(f"sentence 0 and sentence 1: {sin_01:.4f}")
print(f"sentence 0 and sentence 2: {sin_02:.4f}")
print(f"sentence 1 and sentence 2: {sin_12:.4f}")
print()
print(f"similarity(0 vs 1):{sin_01:.4f}")
print(f"similarity(0 vs 2):{sin_02:.4f}")
print(f"similarity(1 vs 2):{sin_12:.4f}")
print()
print("Insight:sentence 0 and 1 have different words but similae meaning")
print("their cosine similarity score is hifh -the embedding captured the meaning")

