# -*- coding: utf-8 -*-
"""Day_4_BigData_PySpark_Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AV31m4cJQIuVi5rT_5qmhQziQJqGB81e
"""

!pip install pyspark --quiet
print('PySpark installation complete!')

# Import PySpark modules and create SparkSession
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import year, month, to_date, col, round as spark_round

import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

spark = SparkSession.builder \
    .appName('Day4_BigData_Sales') \
    .config('spark.sql.adaptive.enabled', 'true') \
    .getOrCreate()

print(f"Spark version : {spark.version}")
print(f'Spark Session : ACTIVE')

df_bronze = spark.read \
       .option('header', 'true') \
       .option('inferSchema', 'true') \
       .csv('large_sales_data.csv')

print('=== BRONZE LAYER - Raw Data ===')
print(f'Rows : {df_bronze.count()}')
print(f'Columns : {len(df_bronze.columns)}')
print(f'Names : {df_bronze.columns}')
print()
df_bronze.printSchema()

# Inspect first rows and summary statistics

print("First 5 rows:")
df_bronze.show(5, truncate=False)

print("\nBasic statistics for numeric columns:")
df_bronze.select('quantity', 'unit_price', 'revenue').describe().show()

# Save Bronze layer as Parquet

df_bronze.write \
       .mode('overwrite') \
       .parquet('sales_bronze.parquet')

print('Bronze Parquet saved: sales_bronze.parquet')

# Compare file sizes
import os

def get_dir_size(path):
  """Get total size of a file or directory in KB."""
  if os.path.isfile(path):
    return os.path.getsize(path) / 1024
  total = 0
  for dirpath, dirnames, filenames in os.walk(path):
    for f in filenames:
      total += os.path.getsize(os.path.join(dirpath, f))
  return total / 1024

csv_size = get_dir_size("large_sales_data.csv")
parquet_size = get_dir_size("sales_bronze_parquet")
reduction = (1-parquet_size/csv_size) * 100

print("\ncsv size : {csv_size:.1f} KB")
print("parquet size : {parquet_size:.1f} KB")
print("reduction : {reduction:.1f}% smaller")
print(f'\nAt 1 TB scale: CSV=1000 GB + Parquet={1000*(1-reduction/100):.0f} GB')

# Clean and enrich the data

df_silver = df_bronze  \
      .dropDuplicates() \
      .dropna(subset=['order_id', 'product', 'revenue'])

# Parse the order_date column from string to proper data type
df_silver = df_silver.withColumn(
    'order_date',
    to_date(col('order_date'), 'yyyy-MM-dd')
)

#
df_silver = df_silver \
      .withColumn('order_year', year(col('order_date'))) \
      .withColumn('order_month',month(col('order_date')))
df_silver = df_silver.withColumn(
    'revenue_category',
    F.when(col('revenue')>40000, 'High')
    .when(col('revenue')>10000, 'Medium')
    .otherwise('Low')
)

print(f'Silver layer rows : {df_silver.count()}')
print(f'New columns added: order_year, order_month, revenue_category')
df_silver.select('product', 'revenue', 'order_year', 'order_month', 'revenue_category').show()

df_silver.write\
.mode('overwrite')\
.parquet('sales_silver.parquet')
print("Silver Parquet saved:sales_silver.parquet")
print(f"Silver size:{get_dir_size("sales_silver.parquet"):1f}KB")
df_verify=spark.read.parquet('sales_silver.parquet')
print('\n===Verify Silver layer===')
print(f"Read-back rows:{df_verify.count()} (should match silver count)")
df_verify.printSchema()

top_products = df_silver \
      .groupBy('product') \
      .agg(
          F.sum('revenue').alias('total_revenue'),
          F.count('order_id').alias('num_orders'),
          F.avg('revenue').alias('avg_order_revenue')
      ) \
      .orderBy('total_revenue',ascending=False) \
      .limit(5)
print('===Top 5 products by Revenue===')
top_products.show(truncate=False)

region_revenue = df_silver \
      .groupBy('region') \
      .agg(
          F.sum('revenue').alias('total_revenue'),
          F.count('order_id').alias('num_orders'),
          F.countDistinct('customer_name').alias('num_customers')
      ) \
      .orderBy('total_revenue',ascending=False)

print(' === Revenue by Region ===')
region_revenue.show(truncate=False)

df_silver = df_silver \
    .withColumn("month_num", F.month("order_date")) \
    .withColumn("order_month", F.date_format("order_date", "MMM"))

monthly_trend = df_silver \
    .groupBy("month_num", "order_month") \
    .agg(
        F.sum("revenue").alias("monthly_revenue"),
        F.count("order_id").alias("monthly_orders")
    ) \
    .orderBy("month_num") \
    .drop("month_num")
monthly_trend.show(truncate=False)

gold_region = region_revenue
gold_region.write.mode("overwrite").parquet('gold_region_revenue.parquet')
print("Gold 1 saved: gold_region_revenue.parquet")

gold_products = df_silver \
     .groupBy('product', 'category') \
     .agg(
         F.sum('revenue').alias('total_revenue'),
         F.count('order_id').alias('units_sold'),
         spark_round(F.avg('revenue').alias('largest_order')),
         F.max('revenue').alias('largest_order')
     ) \
     .orderBy('total_revenue', ascending=False)

gold_products.write.mode("overwrite").parquet('gold_products_summary.parquet')
print("Gold 2 saved : gold_product_summary.parquet")

gold_products.write.mode("overwrite").parquet('gold_monthly_trend.parquet')
print("Gold 3 saved : gold_monthly_trend.parquet")

monthly_trend.write.mode('overwrite').parquet('gold_monthly_trend.parquet')
region_pd = spark.read.parquet('gold_region_revenue.parquet').toPandas()
product_pd = spark.read.parquet('gold_products_summary.parquet').toPandas()
monthly_pd = spark.read.parquet('gold_monthly_trend.parquet').toPandas()

print('Gold tables converted to Pandas:')
print(f' Region : {region_pd.shape}')
print(f' Products : {product_pd.shape}')
print(f' Monthly : {monthly_pd.shape}')

region_pd = region_pd.sort_values('total_revenue', ascending=False)
product_pd = product_pd.sort_values('total_revenue', ascending=False)
monthly_pd = monthly_pd.sort_values('order_month')

fig,axes=plt.subplots(2,2,figsize=(18,13))
fig.suptitle(
    'Big Data Sales Dashboard-- PySpark Mendalian Pipeline\n'
    '5000 Orders \Processed with Apache Spark',
    fontsize=18,fontweight='bold',color='#1E2761',y=1.01
    )
colors4=['#4FC3F7','#00897B','#E67E22','#8E44AD','#E74C3C']

#--------panel 1:Revenue by region---------------------


ax1 = axes[0][0]
bars1 = ax1.bar(region_pd['region'], region_pd['total_revenue'],
                color=colors4[:len(region_pd)], edgecolor='white')

for bar in bars1:
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height()*1.01,
             f'${bar.get_height()/1e6:.1f}M',
             ha='center', fontsize=10,fontweight='bold',color='#1E2761')
ax1.set_title('Total Revenue by Region', fontsize=14, fontweight='bold')
ax1.set_ylabel('Revenue ($)')
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))

ax1.grid(axis='y', alpha=0.3, linestyle='--')


#--------panel 2:Top Products(horizontal)---------------------


ax2 = axes[0][1]
top_products = product_pd.head(5)
bars2 = ax2.barh(top_products['product'], top_products['total_revenue'],
                color=colors4[:len(top_products)], edgecolor='white')

for bar in bars2:
    ax2.text(bar.get_width() * 1.01,bar.get_y() + bar.get_height() / 2,
             f'${bar.get_width()/1e6:.1f}M',
             va='center', fontsize=10,fontweight='bold',color='#1E2761')
ax2.set_title('Total 5 Products by Revenue', fontsize=14, fontweight='bold')
ax2.set_xlabel('Revenue ($)')
ax2.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))

ax2.grid(axis='x', alpha=0.3, linestyle='--')


# Panel - 3
ax3 = axes[1][0]
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
monthly_labels = [m for m in monthly_pd['order_month']]

ax3.plot(monthly_labels, monthly_pd['monthly_revenue'],
         marker='o', linewidth=2.5, color='#00897B',
         markersize=8, markerfacecolor='white', markeredgewidth=2)

ax3.fill_between(range(len(monthly_labels)),
                 monthly_pd['monthly_revenue'],
                 alpha=0.15, color='#00897B')

ax3.set_title('Monthly Revenue Trend', fontsize=14, fontweight='bold')
ax3.set_ylabel('Revenue ($)')
ax3.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
ax3.grid(alpha=0.3, linestyle='--')
ax3.tick_params(axis='x', rotation=30, labelsize=9)


# Panel - 4
ax4 = axes[1][1]
rev_cat = df_silver.groupBy('revenue_category') \
    .count().orderBy('revenue_category').toPandas()
ax4.pie(rev_cat['count'],
        labels = rev_cat['revenue_category'],
        colors = ['#27AE60', '#E67E22', '#E74C3C'],
        autopct = '%1.1f%%', startangle=90,
        wedgeprops = {'edgecolor': 'white', 'linewidth' :2})
ax4.set_title('Orders by Revenue Category\n(High > $40k | Medium > $10k | Low)', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig('big_data_dashboard.png', dpi = 150, bbox_inches='tight')
plt.show()
print('Dashboard saved: big_data_dashboard.png')

