# -*- coding: utf-8 -*-
"""Day3MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16AivLjKgHXIZOVvy0mMrGoz26REKI27K
"""

pip install requests pandas

import requests
api_key = "0621aafecf91f2a84cdd39294c870557"
city = "Coimbatore"
url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
response = requests.get(url)
print(response.json())

import pandas as pd
weather_data = {
    "City": ["Coimbatore"],
    "Temperature": [31],
    "Feels_like": [33],
    "Humidity": [62],
    "Pressure": [1009],
    "Weather": ["clear sky"],
    "Wind_speed": [2.5]
}
df = pd.DataFrame(weather_data)
df.columns = df.columns.str.lower()
df.to_csv("weather_data.csv", index=False)
print("Weather ETL completed successfully!")
print(df)

import pandas as pd
data = {
    "city": ["Coimbatore"],
    "temperature": [31],
    "feels_like": [33],
    "humidity": [62],
    "pressure": [1009],
    "weather": ["clear sky"],
    "wind_speed": [2.5]
}

df = pd.DataFrame(data)
df.to_csv("weather_data.csv", index=False)
print("CSV file created successfully!")

import pandas as pd
data = {
    "Employee Name": [
        "Ravi", "Priya", "Arun", "Priya", "Meena",
        None, "Kumar", "Divya", "Suresh", "Anitha",
        "Sathiya", "Lakshmi", "Karthik", "Nisha", "Harish",
        "Sanjay", "Deepa", "Rahul", "Sneha", "Manoj",
        "Keerthi", "Ajay", "Pooja", "Varun", "Shalini"
    ],

    "Department": [
        "IT", "HR", "IT", "HR", "Finance",
        "IT", "Marketing", "HR", "Finance", "IT",
        "Marketing", "Finance", "HR", "IT", "Marketing",
        "Finance", "IT", "HR", "Marketing", "Finance",
        "IT", "HR", "Marketing", "Finance", "IT"
    ],

    "Salary": [
        35000, 30000, 40000, 30000, None,
        38000, 42000, 32000, 45000, 39000,
        41000, None, 34000, 37000, 43000,
        46000, 36000, 33000, 44000, 47000,
        None, 35000, 42000, 48000, 39000
    ]
}
df = pd.DataFrame(data)
df.to_excel("employee_salary.xlsx", index=False)
print("employee_salary.xlsx created successfully!")
print(df)

import pandas as pd
df = pd.read_excel("employee_salary.xlsx")
print("Original Data:")
print(df)
df = df.drop_duplicates()
df["Employee Name"] = df["Employee Name"].fillna("Unknown")
avg_salary = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(avg_salary)
df.to_csv("cleaned_employee_salary.csv", index=False)
print("\nEmployee Salary ETL completed successfully!")
print(df)